### ISSUE TITLE
ThemeSnippet not working : all options are greyed-out

### ISSUE THREAD

**Issue by Dark-Dominion** [TanninOne/vortex-theme-snippets#2]
I have installed ThemeSnippet in Vortex and all the optionscare visible, but greyed-out.
There is no way to activate the options.

I have other extensions installed, but even removing them doesn't help.

Screenshot.
![Vortex ThemeSnippet](https://user-images.githubusercontent.com/45037827/172175281-2f453fab-761a-4de8-97f7-e2b6c034da62.png)

**Comment by TanninOne** [comment]
All options on the themes screen are grayed out because you first have to clone a theme before you can make local edits!

**Comment by Dark-Dominion** [comment]
Thank you for clarifying, everything is working.

Would it be possible to lock the width of the first column of the mod page when you check to option "No line wrap in mods table"?
![Vortex ThemeSnippet2](https://user-images.githubusercontent.com/45037827/172718163-5fffcfc8-0d14-4af3-a680-3786d9771095.png)

Because now it looks like this :
![Vortex ThemeSnippet2a](https://user-images.githubusercontent.com/45037827/172718276-f90984d9-73ec-4038-abb9-02eee384d4d1.png)

and I think most people would like this :
![Vortex ThemeSnippet2b](https://user-images.githubusercontent.com/45037827/172718368-263c9627-ef99-4969-a129-e5e124c6ee81.png)

I have been playing around in the .scss, but I have a hard time finding the proper class to set the max-width to 11em.
Thank you for your time, much appreciated
Cheers
-=DD=-
